sudo: false
language: generic

cache:
  apt: true

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5 CODECOV=1
      addons:
        apt:
          packages:
            - g++-5
            - lcov
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
    - env: CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          packages:
            - g++-4.9
          sources: *sources
    - env: CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
          sources: *sources
    - env: CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          packages:
            - clang-3.6
          sources: *sources
script:
     - mkdir -p build
     - cd build
     - cmake -DCMAKE_BUILD_TYPE=Debug -DKERN_TESTING=on ..
     - make
     - ./tests/tests

after_success:
    - |
      if [[ "${CODECOV}" == "1" ]]; then
        cd ${TRAVIS_BUILD_DIR}
        lcov --directory . --capture --output-file coverage.info # capture coverage info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
        lcov --list coverage.info #debug info
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
      fi
